---
name: dist

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Black
      run: |
        python -m pip install black
        black --check --diff  .

  build:
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}

    - name: Install build dependencies
      run: |
        python -m pip install 'robotpy-build>=2020.0.7'
        python -m robotpy_build build-dep --install

    - name: Build wheel
      run: python setup.py bdist_wheel
    
    - name: Publish wheel to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}

  publish-sdist:
    runs-on: ubuntu-latest
    needs: [check]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: python -m pip install robotpy-build
    - name: Build packages
      run: python setup.py sdist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}