---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  ping:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: TheTripleV/build-actions/ping-meta@ping-meta
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
